[build-system]
requires = [
    "setuptools>=61.0.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "project_patcher"
version = "0.1.0.dev1"
authors = [
    { name = "Aaron Haim", email = "ahaim@wpi.edu" }
]
description = "A project runner, diff generator, and patcher rolled into one"
requires-python = ">=3.7"

[tools.setuptools.packages.find]
where = ["src"]
